### ISSUE TITLE
Unable to launch firefox and IE browsers using QAF2.1.9.

### ISSUE THREAD

**Issue by vn01159** [qmetry/qaf#60] opened 2016-12-20 12:57 UTC
Details for Firefox error:
firefox Version 50.1.0
Below error we are getting when running from config file.
Unable to create driver instance in 1st attempt with retry timeout of 0 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance for firefox: Failed to connect to binary FirefoxBinary(C:\Program Files\Mozilla Firefox\firefox.exe) on port 7055; process output follows: null

Details for IE Browser error-
IE driver Server Product version-2.35.1.0
Below error we are getting when running from config file:
Unable to create driver instance in 1st attempt with retry timeout of 0 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance for iexplorer: java.lang.NoSuchMethodException: org.openqa.selenium.ie.InternetExplorerDriver.<init>(java.net.URL, org.openqa.selenium.Capabilities)

**Comment by Priya335021** [comment] 2016-12-26 10:27
Facing same issue while executing with Firefox. 
Additionally below Exception has thrown.
java.lang.RuntimeException: XPathFactory#newInstance() failed to create an XPathFactory for the default object model: http://java.sun.com/jaxp/xpath/dom with the XPathFactoryConfigurationException: javax.xml.xpath.XPathFactoryConfigurationException: java.util.ServiceConfigurationError: javax.xml.xpath.XPathFactory: jar:file:/C:/Users/335021/.ivy2/cache/net.sf.saxon/Saxon-HE/jars/Saxon-HE-9.4.jar!/META-INF/services/javax.xml.xpath.XPathFactory:2: Illegal configuration-file syntax

**Comment by amitbhoraniya** [comment] 2016-12-28 14:46
In order to working with latest version  of firefox ( Firefox 47.0 +) 
1. you need to use selenium 3, make sure you have added selenium3 dependency.
For example: in ivy
```
<dependency org="org.seleniumhq.selenium" name="selenium-remote-driver" rev="3.0.1" />
<dependency org="org.seleniumhq.selenium" name="selenium-java" rev="3.0.1" />
```
2. download the Marionette driver (which is a binary file called geckodriver, and formerly wires) and provide its path to `webdriver.gecko.driver` as a system property in your property file. For instance 
```
system.webdriver.gecko.driver=<gecko driver path>
```
Same way for ie you need to download ie driver and set `webdriver.ie.driver` property.

**Comment by VijayArul** [comment] 2016-12-28 17:10
Thanks amit . we will try this and update the same in the forum

**Comment by vn01159** [comment] 2016-12-29 14:17
Firefox is working fine now with geckodriver v0.11.1 and selenium 3.0.1.

But internet explorer we are getting the below mentioned errors:
com.qmetry.qaf.automation.core.AutomationError: Expected condition failed: Unable to create driver instance in 2nd attempt with retry timeout of 10 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure. (tried for 10 second(s) with 10 SECONDS interval)
java.lang.NoSuchMethodException: org.openqa.selenium.ie.InternetExplorerDriver.<init>(java.net.URL, org.openqa.selenium.Capabilities)

**Comment by Vishnu3012** [comment] 2017-06-21 06:56
I have downloaded the latest IE Driver and set the webdriver.ie.driver = path ( C:\temp\IEDriverServer.exe)
updated driver.name=InternetExplorerDriver
and tried running my scripts, however, I still get the error

Unable to create driver instance in 2nd attempt with retry timeout of 60 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance for internetexplorer: null

What is the issue here? I am able to run the scripts fine on Chrome Browser Though

**Comment by KaranDaCoder** [comment] 2017-07-19 23:10
Just try adding system. before webdriver.ie.driver, and I do not think you need not to 'path()', create a drivers' directory in your project itself and then describe path.
ex: system.webdriver.ie.driver = ./drivers/IEDriverServer.exe   good luck!

**Comment by brianhclark** [comment] 2017-08-01 21:05
Experiencing a similar issue using Selenium 3.4 with QAF 2.1.11. I'm trying to acheive current IE support, but lost Chrome support when moving to the Selenium 3.4. Initially needed to update guava dependancy to 21.0, but now am getting java.lang.NoSuchMethodError: org.openqa.selenium.support.ui.FluentWait.withMessage(Lcom/google/common/base/Supplier;)Lorg/openqa/selenium/support/ui/FluentWait;

I know several of Selenium's supporting dependencies have updated (httpclient, httpcore, guava, gson, commons-codec)), and I attempted updating these in the project with no change in behavior. 

What is the latest supported Selenium server version to use with QAF2.1.11?

**Comment by cjayswal** [comment] 2017-08-02 04:17
Refer #118 for using selenium version 3+.
For selenium 3.4.0 QAF 2.1.12RC-2 is recommended.

**Comment by kchuykov** [comment] 2017-08-23 01:33
Anyone is able to run on any other browser than chrome? i've tried all the suggested combinations of dependencies and no luck

**Comment by cjayswal** [comment] 2017-08-24 14:36
Will you please provide more details about browser version(s), driver version, exception trace?

**Comment by kchuykov** [comment] 2017-08-24 18:54
Thanks a lot, please take a look.

 geckodriver 0.18.0
Firefox 55.0.2 (64-bit)
pom.xml
<dependency>
    <groupId>com.qmetry</groupId>
    <artifactId>qaf</artifactId>
    <version>2.1.12-RC3</version>
    <exclusions>
    	<exclusion>
    		<groupId>org.seleniumhq.selenium</groupId>
    		<artifactId>selenium-remote-driver</artifactId>
    	</exclusion>
    	<exclusion>
    		<groupId>org.seleniumhq.selenium</groupId>
    		<artifactId>selenium-java</artifactId>
    	</exclusion>
    </exclusions>
</dependency>

<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-server</artifactId>
    <version>3.5.2</version>
 
    <exclusions>
    	<exclusion>
    		<groupId>org.seleniumhq.selenium</groupId>
    		<artifactId>selenium-support</artifactId>
    	</exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-support</artifactId>
    <version>3.0.0</version>
 
</dependency>

Log:

log4j:WARN No appenders could be found for logger (com.qmetry.qaf.automation.testng.pro.QAFAnnotationTransformer2).
log4j:WARN Please initialize the log4j system properly.
1503600581452	geckodriver	INFO	geckodriver 0.18.0
1503600581459	geckodriver	INFO	Listening on 127.0.0.1:9451
Unable to create driver instance in 1st attempt with retry timeout of 0 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance for firefox: browserName was not a boolean
Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
System info: host: 'KC', ip: '192.168.80.1', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_20'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:           0x4bb74f - <no info>
   1:           0x4bbea9 - <no info>
   2:           0x43ce8d - <no info>
   3:           0x439481 - <no info>
   4:           0x43dae5 - <no info>
   5:           0x447acf - <no info>
   6:           0x4203e1 - <no info>
   7:           0x407dc7 - <no info>
   8:           0x6d95b9 - <no info>
   9:           0x4173a7 - <no info>
  10:           0x6d38b3 - <no info>
  11:     0x7fff49d02774 - BaseThreadInitThunk
SKIPPED: smokeTest_1([])
         Smoke Test Scenario CRM
com.qmetry.qaf.automation.core.AutomationError: Expected condition failed: Unable to create driver instance in 1st attempt with retry timeout of 0 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure. (tried for 0 second(s) with 10 SECONDS interval)
browserName was not a boolean
Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
System info: host: 'KC', ip: '192.168.80.1', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_20'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:           0x4bb74f - <no info>
   1:           0x4bbea9 - <no info>
   2:           0x43ce8d - <no info>
   3:           0x439481 - <no info>
   4:           0x43dae5 - <no info>
   5:           0x447acf - <no info>
   6:           0x4203e1 - <no info>
   7:           0x407dc7 - <no info>
   8:           0x6d95b9 - <no info>
   9:           0x4173a7 - <no info>
  10:           0x6d38b3 - <no info>
  11:     0x7fff49d02774 - BaseThreadInitThunk
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse$$Lambda$108/253011924.apply(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.W3CHandshakeResponse$$Lambda$110/698741991.apply(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:359)
	at org.openqa.selenium.remote.ProtocolHandshake$$Lambda$111/127702987.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:362)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:641)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:254)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:103)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:137)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.qmetry.qaf.automation.ui.UiDriverFactory.getDriverObj(UiDriverFactory.java:250)
	at com.qmetry.qaf.automation.ui.UiDriverFactory.access$4(UiDriverFactory.java:245)
	at com.qmetry.qaf.automation.ui.UiDriverFactory$Browsers.getDriver(UiDriverFactory.java:428)
	at com.qmetry.qaf.automation.ui.UiDriverFactory$Browsers.access$6(UiDriverFactory.java:416)
	at com.qmetry.qaf.automation.ui.UiDriverFactory.getDriver(UiDriverFactory.java:228)
	at com.qmetry.qaf.automation.ui.UiDriverFactory.get(UiDriverFactory.java:94)
	at com.qmetry.qaf.automation.core.QAFTestBase$DriverInitExpectedCondition.apply(QAFTestBase.java:511)
	at com.qmetry.qaf.automation.core.QAFTestBase$DriverInitExpectedCondition.apply(QAFTestBase.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.qmetry.qaf.automation.core.QAFTestBase.init(QAFTestBase.java:410)
	at com.qmetry.qaf.automation.core.QAFTestBase.getUiDriver(QAFTestBase.java:198)
	at com.qmetry.qaf.automation.ui.WebDriverTestBase.getDriver(WebDriverTestBase.java:47)
	at com.qmetry.qaf.automation.ui.WebDriverTestBase.getDriver(WebDriverTestBase.java:1)
	at com.qmetry.qaf.automation.ui.AbstractTestPage.<init>(AbstractTestPage.java:86)
	at com.qmetry.qaf.automation.ui.AbstractTestPage.<init>(AbstractTestPage.java:93)
	at com.qmetry.qaf.automation.ui.WebDriverBaseTestPage.<init>(WebDriverBaseTestPage.java:62)
	at com.qmetry.qaf.automation.ui.WebDriverBaseTestPage.<init>(WebDriverBaseTestPage.java:58)
	at testing.crm.pages.browser.FFCRMBrowserDashboardPage.<init>(FFCRMBrowserDashboardPage.java:12)
	at testing.crm.testsuits.browser.SmokeTest.smokeTest_1(SmokeTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)


===============================================
    Default test
    Tests run: 1, Failures: 0, Skips: 1
===============================================


===============================================
Default suite
Total tests run: 1, Failures: 0, Skips: 1
===============================================

**Comment by kchuykov** [comment] 2017-08-24 19:11
Same setup as previous but for IE 11 windows 10

log4j:WARN No appenders could be found for logger (com.qmetry.qaf.automation.testng.pro.QAFAnnotationTransformer2).
log4j:WARN Please initialize the log4j system properly.
Started InternetExplorerDriver server (64-bit)
3.5.1.0
Listening on port 8594
Only local connections are allowed
Unable to create driver instance in 1st attempt with retry timeout of 0 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance for iexplorer: Invalid capabilities in firstMatch element 0: browserName is type object instead of string
Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
System info: host: 'KC', ip: '192.168.80.1', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_20'
Driver info: driver.version: InternetExplorerDriver
remote stacktrace: 
SKIPPED: smokeTest_1([])
         Smoke Test Scenario CRM
com.qmetry.qaf.automation.core.AutomationError: Expected condition failed: Unable to create driver instance in 1st attempt with retry timeout of 0 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure. (tried for 0 second(s) with 10 SECONDS interval)
Invalid capabilities in firstMatch element 0: browserName is type object instead of string
Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
System info: host: 'KC', ip: '192.168.80.1', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_20'
Driver info: driver.version: InternetExplorerDriver
remote stacktrace: 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse$$Lambda$94/464224872.apply(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.W3CHandshakeResponse$$Lambda$96/1845623216.apply(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:359)
	at org.openqa.selenium.remote.ProtocolHandshake$$Lambda$97/731829978.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:362)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:641)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:254)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.ie.InternetExplorerDriver.run(InternetExplorerDriver.java:205)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:197)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:156)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.qmetry.qaf.automation.ui.UiDriverFactory.getDriverObj(UiDriverFactory.java:250)
	at com.qmetry.qaf.automation.ui.UiDriverFactory.access$4(UiDriverFactory.java:245)
	at com.qmetry.qaf.automation.ui.UiDriverFactory$Browsers.getDriver(UiDriverFactory.java:428)
	at com.qmetry.qaf.automation.ui.UiDriverFactory$Browsers.access$6(UiDriverFactory.java:416)
	at com.qmetry.qaf.automation.ui.UiDriverFactory.getDriver(UiDriverFactory.java:228)
	at com.qmetry.qaf.automation.ui.UiDriverFactory.get(UiDriverFactory.java:94)
	at com.qmetry.qaf.automation.core.QAFTestBase$DriverInitExpectedCondition.apply(QAFTestBase.java:511)
	at com.qmetry.qaf.automation.core.QAFTestBase$DriverInitExpectedCondition.apply(QAFTestBase.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.qmetry.qaf.automation.core.QAFTestBase.init(QAFTestBase.java:410)
	at com.qmetry.qaf.automation.core.QAFTestBase.getUiDriver(QAFTestBase.java:198)
	at com.qmetry.qaf.automation.ui.WebDriverTestBase.getDriver(WebDriverTestBase.java:47)
	at com.qmetry.qaf.automation.ui.WebDriverTestBase.getDriver(WebDriverTestBase.java:1)
	at com.qmetry.qaf.automation.ui.AbstractTestPage.<init>(AbstractTestPage.java:86)
	at com.qmetry.qaf.automation.ui.AbstractTestPage.<init>(AbstractTestPage.java:93)
	at com.qmetry.qaf.automation.ui.WebDriverBaseTestPage.<init>(WebDriverBaseTestPage.java:62)
	at com.qmetry.qaf.automation.ui.WebDriverBaseTestPage.<init>(WebDriverBaseTestPage.java:58)
	at test.crm.pages.browser.FFCRMBrowserDashboardPage.<init>(FFCRMBrowserDashboardPage.java:12)
	at test.crm.testsuits.browser.SmokeTest.smokeTest_1(SmokeTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)

**Comment by cjayswal** [comment] 2017-08-27 06:49
One of the observation from stack trace is `browserName` error. Are you setting browser name using capability? If so will you provide what and how you are setting browserName value? Are you running your test with proxy?

I am not able to reproduce the problem. Following is found working fine on Windows 10:
**Firefox:**
Version:  55.0.3 (64-bit)
Gecko Driver: geckodriver-v0.18.0-win64

```
driver.name=firefoxDriver
system.webdriver.gecko.driver=<path>/geckodriver.exe
```

**IE:**
Version: 11.540.15063.0
IE Driver server: IEDriverServer_x64_3.5.1
```
driver.name=iexplorerDriver
system.webdriver.ie.driver=<path>/IEDriverServer.exe
```
I would suggest to try a simple driver code (may be main method with creating driver and google search) without QAF to ensure it's working fine with plain driver but not working when using QAF.

Problem doesn't looks of QAF, either it's something related to your local environment or driver specific issue should be posted on selenium group and/or issue.

**Comment by kchuykov** [comment] 2017-08-27 10:47
got it working by changing the order of dependencies in the pom file... I put selenium first and QAF last.

**Closed** 2017-08-27 17:09 UTC
Labels: driver, help wanted

**Comment by akhiljosephk** [comment] 2018-01-02 14:21
I am facing this issue with latest Selenium and QAF. 

CHROME:
Works fine with Chrome. 
The driver session for Chrome is (Example) QAFExtendedWebDriver: chrome on XP (979a57328b5f984cecf90b71689e8970)

IE:
IE opens but doesn't navigate to the URL. 
org.openqa.selenium.remote.SessionNotFoundException: session null does not exist
The driver session for IE is QAFExtendedWebDriver:  on ANY (null)

FIREFOX:
Firefox instance opens but doesn't navigate to the URL. 
Unable to Create Driver Instance for firefox: Failed to connect to binary FirefoxBinary(C:\Program Files\Mozilla Firefox\firefox.exe)

**Comment by anxx15** [comment] 2019-05-13 00:26
For folks who are having trouble with IE can change the IE security settings and make sure the protection modes are at same level (either enabled or disabled for all). If your IT security does not allow this change, add the following lines to the application.properties file. And change the Zoom level to 100%

ieexplorer.additional.capabilities={'ignoreProtectedModeSettings':true, 'nativeEvents':true, 'ignoreZoomSetting':true}

Hope this works.
