### ISSUE TITLE
Test fails on NullPointerException when using verify functions

### ISSUE THREAD

**Issue by hadasshani** [qmetry/qaf#57] opened 2016-12-07 14:05 UTC
#

**Comment by hadasshani** [comment] 2016-12-07 14:22
When i'm using verify functions it fails the step correctly but it is also fails the test on null pointer exception. 
It happens if I'm executing from testNG or executing from the pom file.
![2016-12-07_16h13_08](https://cloud.githubusercontent.com/assets/10271179/20970888/0fbff2ec-bc98-11e6-8bb0-012b3bc1513b.png)
![2016-12-07_16h13_36](https://cloud.githubusercontent.com/assets/10271179/20971191/2d86b2c4-bc99-11e6-9b05-72672b409c4e.png)
![2016-12-07_16h21_54](https://cloud.githubusercontent.com/assets/10271179/20971226/47da8cf4-bc99-11e6-9c7f-ed2c9d2b30fb.png)

**Comment by cjayswal** [comment] 2016-12-07 14:32
Are you facing this while running outside  IntelliJ or running using maven/ant? It looks like issue of  IntelliJ TestNG plugin.

**Comment by hadasshani** [comment] 2016-12-07 14:35
I’ll check in eclipse and outside of ide

**Comment by hadasshani** [comment] 2016-12-07 15:00
I have the same issue running from eclipse and from command line. In this cases I get "An error occurred" and test is failed

**Comment by cjayswal** [comment] 2016-12-07 15:20
Alternately you can run using maven or ant (instead of run as TestNG test).

**Comment by hadasshani** [comment] 2016-12-07 15:23
I'm using maven to execute the testNG from eclipse or cmd.

**Comment by cjayswal** [comment] 2016-12-08 03:51
This is from [IDEATestNGRemoteListener](https://github.com/JetBrains/intellij-community/blob/master/plugins/testng_rt/src/org/testng/IDEATestNGRemoteListener.java)#213. Can you share step to reproduce?

**Comment by hadasshani** [comment] 2016-12-08 07:34
Please explain why do you think it is intelliJplugin – I have the same problem in eclipse with eclipse testng plugin, and when I’m executing from command line

**Comment by Ivanrogacev** [comment] 2017-03-15 16:34
I have same issue in IntelliJ 2016.3 and QAF 2.1.10. 
Following test will NPE:
verifyFalse("123".equals("123"), "f", "p");
--------------------------------------------------
java.lang.NullPointerException
	at org.testng.IDEATestNGRemoteListener.onTestFailure(IDEATestNGRemoteListener.java:213)
	at org.testng.IDEATestNGRemoteListener.onTestFailure(IDEATestNGRemoteListener.java:107)
	at org.testng.IDEATestNGTestListener.onTestFailure(IDEATestNGTestListener.java:34)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1691)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1675)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:700)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:805)
	at org.testng.TestRunner.run(TestRunner.java:655)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by Ivanrogacev** [comment] 2017-03-15 17:45
IntelliJ IDEA fixed this issue https://youtrack.jetbrains.com/issue/IDEA-167298

**Comment by cjayswal** [comment] 2017-03-16 15:52
Thanks @Ivanrogacev for update. Please let us know if still any issue with QAF or we can close this issue.

**Comment by Ivanrogacev** [comment] 2017-03-24 15:15
@cjayswal tested on IntelliJ: Version: 2017.1, Build: 171.3780.107, Released: March 21, 2017. Everything is working as expected

**Comment by cjayswal** [comment] 2017-03-24 16:33
@Ivanrogacev, Thanks for confirmation. Closing the issue.

**Closed by cjayswal** 2017-03-24 16:33 UTC
Labels: third-party
