### ISSUE TITLE
 Optional parameter in step

### ISSUE THREAD

**Issue by hadasshani** [qmetry/qaf#139] opened 2017-09-18 07:37 UTC
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
    1. Define step @And("^I click \"(.*?)\"(?: for \"(.*?)\")?$")  (with optional parameter)
    2. When use. : I click “Options” for “GGGG” 
    3. Get 

java.lang.NullPointerException 
at java.util.regex.Matcher.getTextLength(Matcher.java:1283) 
at java.util.regex.Matcher.reset(Matcher.java:309) 
at java.util.regex.Matcher.<init>(Matcher.java:229) 
at java.util.regex.Pattern.matcher(Pattern.java:1093) 
at com.qmetry.qaf.automation.step.client.text.BDDDefinitionHelper$ParamType.getType(BDDDefinitionHelper.java:126) 
at com.qmetry.qaf.automation.step.BDDStepMatcherFactory$GherkinStepMatcher.getArgsFromCall(BDDStepMatcherFactory.java:91) 
at com.qmetry.qaf.automation.step.StringTestStep.getTestStep(StringTestStep.java:198) 
at com.qmetry.qaf.automation.step.StringTestStep.initStep(StringTestStep.java:78) 
at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:187) 
at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:219) 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:498) 
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104) 
at org.testng.internal.Invoker.invokeMethod(Invoker.java:645) 
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851) 
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177) 
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) 
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) 
at org.testng.TestRunner.privateRun(TestRunner.java:781) 
at org.testng.TestRunner.run(TestRunner.java:635) 
at org.testng.SuiteRunner.runTest(SuiteRunner.java:387) 
at org.testng.SuiteRunner.access$000(SuiteRunner.java:39) 
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421) 
at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64) 
at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
at java.lang.Thread.run(Thread.java:745)

### Expected behavior

This is working for Selenium java cucumber solution

### Is the issue reproductible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment] 2017-09-18 08:01
@hadasshani,
Will you please attache sample code to reproduce the issue which is working fine with cucumber.

**Comment by esskayatpk** [comment] 2017-09-25 12:34
Hi Chirag, there is no actual user code here. This step fails even before it gets to execute the user code in the step definition I have created. Please advise.

Thank you,

**Comment by cjayswal** [comment] 2017-09-25 15:08
It will be helpful if you provide sample to reproduce the issue. Like java method with step declaration, possible step call(s).

**Comment by hadasshani** [comment] 2017-09-26 09:32
java method:
 @Then("^I click \"(.*?)\"(?: for \"(.*?)\")?$")
    public void optionalParameter(String text, String toText) {

        System.out.println("text:" + text + " forText:" + toText);
    }

use steps:
    Then I click "options" for "GGG"
    Then I click "options2"

printed results:
text:options forText:GGG
text:options2 forText:null

**Comment by AbdulShaikhPerfecto** [comment] 2017-10-04 07:34
Hi, Any update on this, when the bug is going to be fixed?

**Comment by cjayswal** [comment] 2017-10-04 14:24
i would suggest to create two different step with overloaded methods instead.

**Comment by esskayatpk** [comment] 2017-10-05 14:55
Hey Abdul, are you using QAF for mobile automation?

thanks

**Comment by esskayatpk** [comment] 2017-10-05 14:57
Hey Chirag, is there discussion forum where we can ask questions/discuss
QAF topics? Please advise.

thanks

**Comment by AbdulShaikhPerfecto** [comment] 2017-10-09 07:43
@cjayswal : Perfecto's Customer is using the work around, but we need this to be fixed as well. can we have a ETA for the same?

**Comment by cjayswal** [comment] 2017-10-09 15:10
@esskayatpk qaf [users group](https://groups.google.com/forum/#!forum/qaf-users) is forum to ask question and discussion.

**Comment by AbdulShaikhPerfecto** [comment] 2017-10-13 07:38
@cjayswal : So this is not going to be fixed for now?

**Comment by AbdulShaikhPerfecto** [comment] 2017-10-23 07:26
@cjayswal : Any ETA for this?

**Comment by AbdulShaikhPerfecto** [comment] 2017-10-31 07:22
@cjayswal : Are we considering this to be fixed in near time? or should we ask our customers to proceed with workaround only?

**Comment by cjayswal** [comment] 2017-11-01 14:49
In fact, suggested way is not work-around but leveraging method overloading. I would recommend that instead of optional args because earlier we found it introduces ambiguity having large number of steps. So my opinion is not to use optional statements to avoid ambiguity.

I appreciate if someone can provide working cucumber project with above example to have faster solution.

**Comment by amitbhoraniya** [comment] 2017-11-02 05:05
@cjayswal [Cucumber Example](https://github.com/amitbhoraniya/cucumber-jvm-example).

**Comment by AbdulShaikhPerfecto** [comment] 2017-11-16 07:07
@cjayswal : Are we considering this to be fixed in near time? or should we ask our customers to proceed with workaround only?

**Closed** 2017-11-26 23:50 UTC
Labels: bdd-gherkin, bug, moderate
