### ISSUE TITLE
NoClassDefFoundError IAnnotationTransformer2 in 2.1.15

### ISSUE THREAD

**Issue by AutomateItEasyWay** [qmetry/qaf#328] opened 2020-03-12 02:02 UTC
### QAF Version
> Note: only the latest version is supported
2.1.15

### Steps To Reproduce
    1. Upgrade testng from 6.10 to 7.1.0
    2. Upgrade qaf from 2.1.13 to 2.1.15

### Expected behavior
Tests that were executed when run on qaf 2.1.13 should still execute on qaf 2.1.15.

### Actual behavior
As soon as I start execution of tests using testng.xml I get an exception

java.lang.NoClassDefFoundError: org/testng/IAnnotationTransformer2
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:961)
at org.testng.TestNG.initializeConfiguration(TestNG.java:898)
at org.testng.TestNG.initializeEverything(TestNG.java:988)
at org.testng.TestNG.run(TestNG.java:999)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.lang.ClassNotFoundException: org.testng.IAnnotationTransformer2
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 23 more

### Is the issue reproducible on runner?

- [ ] QAS
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse

**Comment by AutomateItEasyWay** [comment] 2020-03-13 02:25
@cjayswal Can you please help if there are any more steps I need to follow? I know 2.1.15 supports 7+ version of testng. Not sure if I am missing something obvious.

**Comment by cjayswal** [comment] 2020-03-13 07:16
With 2.1.15, you can't expect to have testng version other than 6.10. Changes after that version broken many of the projects in terms of execution behavior. So 6.10 was locked as it was known stable version. However, considering 6.10 as known stable version of TestNG, upcoming release of qaf will allow later version of TestNG(with users own responsibility).

Duplicate of #174

**Comment by cjayswal** [comment] 2020-03-17 02:31
Required to use TestNG 6.10 with QAF 2.1.15. If you really want to use TestNG 7, you can try QAF `3.0.0-RC1`. Refer [notes](https://github.com/qmetry/qaf/issues/174#issuecomment-590115142) here.

**Closed** 2020-03-17 02:31 UTC
