### ISSUE TITLE
Selenium 3+ causes unable to cast error

### ISSUE THREAD

**Issue by JoshKimbrough** [qmetry/qaf#119] opened 2017-06-19 22:45 UTC
Updating to Selenium 3.4 or 3.0 causes the following error when attempting to locate an element using CSS:
org.openqa.selenium.remote.RemoteWebElement cannot be cast to com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebElement
Stack trace:

Driver info: driver.version: QAFExtendedWebDriver
	at org.openqa.selenium.support.ui.FluentWait.timeoutException(FluentWait.java:296)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:265)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.load(QAFExtendedWebDriver.java:214)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebElement.load(QAFExtendedWebElement.java:284)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebElement.getId(QAFExtendedWebElement.java:294)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebElement.isDisplayed(QAFExtendedWebElement.java:314)
	at com.qmetry.qaf.automation.ui.util.QAFWebElementExpectedConditions$1.apply(QAFWebElementExpectedConditions.java:46)
	at com.qmetry.qaf.automation.ui.util.QAFWebElementExpectedConditions$1.apply(QAFWebElementExpectedConditions.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	... 28 more
Caused by: java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebElement cannot be cast to com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebElement
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.findElementByCssSelector(QAFExtendedWebDriver.java:366)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.findElementByCssSelector(QAFExtendedWebDriver.java:1)
	at org.openqa.selenium.By$ByCssSelector.findElement(By.java:430)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:402)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.findElement(QAFExtendedWebDriver.java:169)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.findElement(QAFExtendedWebDriver.java:1)
	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:895)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:41)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:181)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:178)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)

Using these dependencies:
<dependency>
                <groupId>org.seleniumhq.selenium</groupId>
                <artifactId>selenium-java</artifactId>
                <version>3.4.0</version>
                <exclusions>
                                <exclusion>
                                                <groupId>org.seleniumhq.selenium</groupId>
                                                <artifactId>selenium-support</artifactId>
                                </exclusion>
                </exclusions>
</dependency>
 
<dependency>
                                                <groupId>org.seleniumhq.selenium</groupId>
                                                <artifactId>selenium-support</artifactId>
                                                <version>3.0.0</version>
                                </dependency>
                                
 
                                <dependency>
                                                <groupId>org.seleniumhq.selenium</groupId>
                                                <artifactId>selenium-htmlunit-driver</artifactId>
                                                <version>2.52.0</version>
                                </dependency>
 
                                <dependency>
                                                <groupId>org.seleniumhq.selenium</groupId>
                                                <artifactId>selenium-server</artifactId>
                                                <version>3.4.0</version>
                                </dependency>
 
                                <dependency>
                                                <groupId>org.seleniumhq.selenium</groupId>
                                                <artifactId>selenium-remote-driver</artifactId>
                                                <version>3.4.0</version>
                                </dependency>
 
                                <dependency>
                                                <groupId>org.seleniumhq.selenium</groupId>
                                                <artifactId>selenium-api</artifactId>
                                                <version>3.4.0</version>
                                </dependency>
 
                                <dependency>
                                                <groupId>com.google.guava</groupId>
                                                <artifactId>guava</artifactId>
                                                <version>21.0</version>
                                </dependency>

**Comment by cjayswal** [comment] 2017-06-19 23:34
Hi @JoshKimbrough, Will you please provide steps to reproduce? Sample test/code with error-prone behavior will be useful to quickly reproduce and confirm against before closing this issue.

**Comment by cjayswal** [comment] 2017-07-07 21:54
This is due to visibility change from [commit 9a7082bc993255c1a3484dccdffe054abdae21e4](https://github.com/SeleniumHQ/selenium/commit/9a7082bc993255c1a3484dccdffe054abdae21e4#diff-3a70e626304cacffcc1f2876f31f442f) .Fix has been submitted and requested to merge in https://github.com/SeleniumHQ/selenium/pull/4279.

**Closed** 2017-08-06 14:37 UTC
Labels: bug, driver

**Comment by cjayswal** [comment] 2017-08-09 18:18
Thanks @shs96c

**Comment by nakulkhargonkar** [comment] 2019-03-01 09:57
Upgrading to selenium 3.1 till 3.9 causes the same issue. below is the stack trace.

java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebElement cannot be cast to com.infostretch.automation.webdriver.IsExtendedWebElement
   [testng] 	at com.infostretch.automation.webdriver.IsExtendedWebDriver.findElementByXPath(IsExtendedWebDriver.java:414)
   [testng] 	at com.infostretch.automation.webdriver.IsExtendedWebDriver.findElementByXPath(IsExtendedWebDriver.java:1)
   [testng] 	at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
   [testng] 	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
   [testng] 	at com.infostretch.automation.webdriver.IsExtendedWebDriver.findElement(IsExtendedWebDriver.java:128)
   [testng] 	at com.infostretch.automation.webdriver.IsExtendedWebDriver.findElement(IsExtendedWebDriver.java:1)
   [testng] 	at com.thoughtworks.selenium.webdriven.ElementFinder.xpathWizardry(ElementFinder.java:134)
   [testng] 	at com.thoughtworks.selenium.webdriven.ElementFinder.findElementDirectlyIfNecessary(ElementFinder.java:117)
   [testng] 	at com.thoughtworks.selenium.webdriven.ElementFinder.findElement(ElementFinder.java:87)
   [testng] 	at com.thoughtworks.selenium.webdriven.commands.IsElementPresent.handleSeleneseCommand(IsElementPresent.java:36)
   [testng] 	at com.thoughtworks.selenium.webdriven.commands.IsElementPresent.handleSeleneseCommand(IsElementPresent.java:26)
   [testng] 	at com.thoughtworks.selenium.webdriven.SeleneseCommand.apply(SeleneseCommand.java:36)
   [testng] 	at com.thoughtworks.selenium.webdriven.Timer.run(Timer.java:41)
   [testng] 	at com.thoughtworks.selenium.webdriven.WebDriverCommandProcessor.execute(WebDriverCommandProcessor.java:150)
   [testng] 	at com.thoughtworks.selenium.webdriven.WebDriverCommandProcessor.getBoolean(WebDriverCommandProcessor.java:137)
   [testng] 	at com.thoughtworks.selenium.DefaultSelenium.isElementPresent(DefaultSelenium.java:544)
   [testng] 	at com.tibco.automation.mdm.page.common.LoginPage.isPageActive(LoginPage.java:33)
   [testng] 	at com.infostretch.automation.api.page.BaseTestPage.launchPage(BaseTestPage.java:158)
   [testng] 	at com.tibco.automation.mdm.page.common.LoginPage.launchPage(LoginPage.java:203)
   [testng] 	at com.tibco.automation.mdm.page.common.LoginPage.ensureLoggedInWith(LoginPage.java:163)
   [testng] 	at com.tibco.automation.mdm.page.common.CIMPageTemplate.isPageActive(CIMPageTemplate.java:209)
   [testng] 	at com.tibco.automation.mdm.page.browseandsearch.EditRecordPage.isPageActive(EditRecordPage.java:151)
   [testng] 	at com.infostretch.automation.api.page.BaseTestPage.launchPage(BaseTestPage.java:158)
   [testng] 	at com.tibco.automation.mdm.page.browseandsearch.EditRecordPage.launchPage(EditRecordPage.java:1036)
   [testng] 	at com.tibco.automation.mdm.tests.rulebase.rulebase_designer.RulebaseStudioTestSuite3.MDMS_424(RulebaseStudioTestSuite3.java:208)
   [testng] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   [testng] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   [testng] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   [testng] 	at java.lang.reflect.Method.invoke(Unknown Source)
   [testng] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
   [testng] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:701)
   [testng] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:893)
   [testng] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1218)
   [testng] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
   [testng] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
   [testng] 	at org.testng.TestRunner.privateRun(TestRunner.java:758)
   [testng] 	at org.testng.TestRunner.run(TestRunner.java:613)
   [testng] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
   [testng] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
   [testng] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
   [testng] 	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
   [testng] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
   [testng] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
   [testng] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1170)
   [testng] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1095)
   [testng] 	at org.testng.TestNG.run(TestNG.java:1007)
   [testng] 	at org.testng.TestNG.privateMain(TestNG.java:1315)
   [testng] 	at org.testng.TestNG.main(TestNG.java:1279)


Selenium Version used : 
selenium-server-standalone-3.9.1.jar
selenium-leg-rc-3.6.0.jar 
selenium-support-3.14.0.jar

Similar to this we have tried for other previous selenium releases like 3.14 & 3.3.1 as well.
The above issue is reproducing foe Chrome & IE, but strangely its working good for firefox v60.

Please let us know if we are missing something.

**Comment by shs96c** [comment] 2019-03-02 09:27
The key problem seems to be `org.openqa.selenium.remote.RemoteWebElement cannot be cast to com.infostretch.automation.webdriver.IsExtendedWebElement`. Is there a reproducible test case for this? The error is happening in the RC bindings, which are legacy, so we don't often work in that area.

**Comment by cjayswal** [comment] 2019-03-02 22:00
@nakulkhargonkar it looks that you are using very old version which was available as ISFW.  Will you please provide details of the ISFW version you are using? With older version you should use selenium support version 3.0.

After version 2.1.6 ISFW is available as open source QAF with some class name and package refracting . For example, `IsExtendedWebDriver` in ISFW is `QAFExtendedWebDriver`. It is highly recommended to migrate from ISFW to oss version QAF. You can refer [how to migrate from older version](https://qmetry.github.io/qaf/latest/how_to_migrate_from_older_version.html)
