### ISSUE TITLE
Driver capabilities are not accepting in JSON format while using custom driver name

### ISSUE THREAD

**Issue by yogeshpathrabe** [qmetry/qaf#314] opened 2020-01-17 16:31 UTC
### QAF Version
> 2.1.15

### Steps To Reproduce
    1. Provide the multiple capabilities like below -
       samsung1.additional.capabilities = {\
         'platformName' : 'Android',\
         'manufacturer' : 'Samsung',\
         'driverClass' : 'io.appium.java_client.android.AndroidDriver',\
         'platformVersion' : '8.0.0',\
         'model' : 'Galaxy S8',\
         'appPackage' : 'com.test.test'\
       }
    2. Try initiating driver using following -
        TestBaseProvider.instance().get().setDriver("samsung1Driver");

### Actual behaviour
Drivers are not getting initiated and throwing exception.

### Expected behaviour
Drivers should accept capabilities in JSON format and create the driver instances.

### Current working behaviour
Current version is accepting capabilities one by one like below -

samsung1.capabilities.platformName = Android
samsung1.capabilities.driverClass = io.appium.java_client.android.AndroidDriver
samsung1.capabilities.manufacturer = Samsung
samsung1.capabilities.platformVersion = 8.0.0
samsung1.capabilities.model = Galaxy S8
samsung1.capabilities.appPackage = com.test.test

By passing the capabilities one by one it's working fine.

**Comment by cjayswal** [comment] 2020-01-18 18:53
Duplicate of #241.  This should work with 2.1.15. Make sure the you are using qaf 2.1.15.

**Closed** 2020-01-21 09:09 UTC
Labels: driver, duplicate
