### ISSUE TITLE
 java.lang.NullPointerException exception occurs on passing null test data through test data sheet in QAF 2.1.14 version

### ISSUE THREAD

**Issue by abhishekDautomator** [qmetry/qaf#296] opened 2019-10-16 07:12 UTC
### QAF Version
> Note: only the latest version is supported
QAF 2.1.14 version
### Steps To Reproduce
    1. Pass null value through test data sheet to test a scenario
    2. java.lang.NullPointerException exception occurs on starting the execution.

### Expected behavior
No null pointer exception should comes as it was working earlier with 2.1.10 version. As i have to validate a scenario involving null test data

### Actual behavior
java.lang.NullPointerException exception occurs

### Is the issue reproducible on runner?

- [ ] Eclipse
- [ ] IntelliJ

### Test case sample
> 

login | platform | server | user | pass |  
-- | -- | -- | -- | -- | --
  | Machine Learning Platform | rwaiml.solutions |   |   |  
  | Machine Learning Platform | rwaiml.solutions | octopus |   |  
  | Machine Learning Platform | rwaiml.solutions |   | password |  
  | Machine Learning Platform | rwaiml.solutions | octopus | password | login

**Comment by cjayswal** [comment] 2019-10-16 15:57
Looks duplicate of #269. Try 2.1.15-beta-3

**Closed** 2019-11-08 08:23 UTC
Labels: duplicate
