### ISSUE TITLE
need help with transforming glob to regexp when running tests in FF

### ISSUE THREAD

**Issue by Manolo2014** [qmetry/qaf#147] opened 2017-10-04 20:28 UTC
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
    1. when running tests using QAF the following assertion, is causing an error:
assertCssStyle("customer.name","cursor", "not-allowed"); 

### Expected behavior
Assertion should be met or throw exception, and this is working with Chrome

### Actual behavior
when testing in Firefox, I am getting this error

[WebDriverCommandLogger] - Executing findElement parameters: {"using":"xpath","value":"//div[1]/div[@id='ticket-list']/div[2]/div[1]//div[@class='ticket-title']"}
[WebDriverCommandLogger] - command: findElement[ param-1: {value=//div[1]/div[@id='ticket-list']/div[2]/div[1]//div[@class='ticket-title'], using=xpath}] Result: id: 25d623d9-bc07-4e33-bac5-ce1ac2d00e44
[WebDriverCommandLogger] - Executing getElementValueOfCssProperty element: By.xpath: //div[1]/div[@id='ticket-list']/div[2]/div[1]//div[@class='ticket-title'] parameters: {"propertyName":"border-left","id":"25d623d9-bc07-4e33-bac5-ce1ac2d00e44"}
[WebDriverCommandLogger] - command: getElementValueOfCssProperty[ param-1: By.xpath: //div[1]/div[@id='ticket-list']/div[2]/div[1]//div[@class='ticket-title'] param-2: {"propertyName":"border-left","id":"25d623d9-bc07-4e33-bac5-ce1ac2d00e44"}] Result: getElementValueOfCssProperty:
expected "7px solid rgb(183, 18, 52)" to match glob "" (had transformed the glob into regexp ""

### Is the issue reproductible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
this is my test case
    @QAFDataProvider(dataFile = "resources/TestData/ticketingData/newTicket.json")
    @Test(description = "This is testing the default Customer Name and Customer Email values")
    public void newTicketPopupDefaults(Map<String, String> data) {
        get("");
        successlogin(data.get("Email"), data.get("Pwd"));
        goToTicketing();
        newTktPopup();
        waitForVisible("newticket.header",5);
        waitForVisible("customer.name",5);
        try {
            assertCssStyle("customer.name","cursor", "not-allowed");
        } catch (AssertionError e) {
            e.printStackTrace();
        }
        waitForVisible("customer.email",5);
        try {
            assertCssStyle("customer.email","cursor", "not-allowed");
        } catch (AssertionError e) {
            e.printStackTrace();
        }
        assertPresent("//a[@id='dzAttachments']");
        waitForEnabled("cancel.button");
        click("cancel.button");
        logout();

    }

**Comment by cjayswal** [comment] 2017-10-05 13:06
Different browsers has deference rendering engine so for such validation you need to have cross-browser implementation. This is not QAF issue(bug or feature request). Will you please close this issue here and move this to [users group](https://groups.google.com/forum/#!forum/qaf-users)? While posting to user group share detailed stack-trace of exception, and provide steps to reproduce. The code you share will not reproduce the issue because one may not be able to run it.

**Closed** 2017-10-05 16:09 UTC
Labels: driver, help wanted, third-party

**Comment by cjayswal** [comment] 2017-10-06 15:27
I didn't find post in [users group](https://groups.google.com/forum/#!forum/qaf-users). Did you resolved your problem? even if resolved it would be good to have in users group for benefit of other users. Don't forgot to share code that can be used to reproduce the behavior.

Thanks,
Chirag
