### ISSUE TITLE
Byte value is being read as 2.0 instead of 2 when read from excel sheet in QAF latest version

### ISSUE THREAD

**Issue by ashoksagi** [qmetry/qaf#431] opened 2022-11-02 19:26 UTC
### QAF Version
> Note: only the latest version is supported
3.1.0
### Steps To Reproduce
    1. Read a byte value from excel from feature file example table
    2.Like below
       Scenario Outline: Cell Data Types in Excel
       Given The "char" should be taken as "<char>"
	Examples: {datafile:'ExcelDataTest.xls',sheetName:'ExcelTest'}

### Expected behavior
Value should be read as 2

### Actual behavior
It is being read as 2.0

### Is the issue reproducible on runner?

- [X ] Maven
- [ X] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
   Scenario Outline: Cell Data Types in Excel
       Given The "char" should be taken as "<char>"
	Examples: {datafile:'ExcelDataTest.xls',sheetName:'ExcelTest'}

**Comment by cjayswal** [comment] 2022-11-04 16:26
Duplicate of #416 
you can set cell/column format string (Text or @) in excel.

**Comment by cjayswal** [comment] 2023-07-12 22:17
closing as duplicate

**Closed by cjayswal** 2023-07-12 22:17 UTC
Labels: duplicate
