### ISSUE TITLE
Unable to integrate Selenium 4.4.0 and above version with qaf version 3.1.0 or 3.2.0b 

### ISSUE THREAD

**Issue by mohan388** [qmetry/qaf#437] opened 2023-01-10 13:35 UTC
### QAF 3.1.0, 3.2.0b
> Note: only the latest version is supported

### Steps To Reproduce
    1. Open the package com.qmetry.qaf.automation.ui.webdriver and navigate to QAFWebDriver class file

### Expected behavior
The below import classes should be removed as they are not available in selenium 4.4.0 and above 
import org.openqa.selenium.interactions.HasInputDevices";
import org.openqa.selenium.interactions.Keyboard";
import org.openqa.selenium.interactions.Mouse";
import org.openqa.selenium.interactions.TouchScreen";

### Actual behavior
The deprecated classes are still imported and unable to build projects with Selenium 4.4.0 and Qaf 3.1.0

### Is the issue reproducible on runner?
Yes, always reproducible
- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment] 2023-01-10 21:26
Duplicate of #425

**Comment by cjayswal** [comment] 2023-07-12 21:59
Closing as duplicate issue.

**Closed by cjayswal** 2023-07-12 21:59 UTC
Labels: duplicate

**Comment by Kirthika88** [comment] 2024-02-26 05:25
Hello ,

I have updated my QAF jar to 4.0.0-RC2  and selinium 4.11.0 with java 1.8 , my FIle upload scenario is not working below is my code 
@QAFTestStep(description = "I upload file from mylocal {PARAM_0}") /* PARAM_0 = filename */
	public void STEPDEF_65d8658901b18502ff21d78c(String PARAM_0) throws Exception {QAFExtendedWebDriver driver = new WebDriverTestBase().getDriver();
	System.out.println("Before local file detector");
	String fileToUpload = new File(PARAM_0).getAbsolutePath();
	System.out.println("fileupload " + fileToUpload);
	Path path = Paths.get(fileToUpload);
	System.out.println("Real path:" + path.toRealPath().toString());
	driver.setFileDetector(new LocalFileDetector());
	QAFWebElement elem = driver.findElement("//input[@type='file']");
	//JavascriptExecutor jsx = (JavascriptExecutor) driver;
	//jsx.executeScript("document.getElementById('//input[@type='file']').value='" + path.toRealPath().toString() + "';");

//	System.out.println("After local file elem" + elem);
	System.out.println("After local file detector");
//elem.click();
//'type' the file location to it as it were a usual <input type='text' /> element
    System.out.println("fileToUpload:"+fileToUpload);
	elem.sendKeys(path.toRealPath().toString());
	System.out.println("After local file detector Ended");	}
}


samething worked with qaf 3.2 ,selnium 3.141.59 can you please help
