### ISSUE TITLE
Getting Null Pointer exception when running tests in class under default package

### ISSUE THREAD

**Issue by kabothu** [qmetry/qaf#250] opened 2019-03-19 04:52 UTC
I'm using 2.1.13 maven dependency and I have my tests something like, and When I run my tests I'm getting null pointer exception with below stack trace. Could you please help me?

public class SimpleGoogleTest {

@QAFDataProvider(dataFile = "/Users/TesUser/Workspace/FixProject/ExcelCheck/src/test/resources/excelfile.xls", sheetName = "excelreader")
@Test()
public void testGoogleData(Map<String, Object> data)

{ System.out.println(data.get("name")); }
}

FAILED: testGoogleData
java.lang.NullPointerException
at com.qmetry.qaf.automation.testng.pro.QAFTestNGListener.afterInvocation(QAFTestNGListener.java:208)
at com.qmetry.qaf.automation.testng.pro.QAFTestNGListener2.afterInvocation(QAFTestNGListener2.java:158)
at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithContextStrategy.callMethod(InvokedMethodListenerInvoker.java:108)
at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithContextStrategy.callMethod(InvokedMethodListenerInvoker.java:104)
at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:552)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)

**Comment by cjayswal** [comment] 2019-03-19 17:03
@kabothu , i am not able to reproduce this issue. Will you please debug it and provide steps to reproduce? I see that you have typo in above code sample  `@test()` instead of `@Test`.

**Comment by kabothu** [comment] 2019-03-19 17:53
@cjayswal : Please follow the steps below:

Add these maven dependencies to pom.xml

<dependency>
<groupId>com.qmetry</groupId>
<artifactId>qaf</artifactId>
<version>2.1.13</version>
</dependency>
<dependency>

<dependency>
<groupId>org.testng</groupId>
<artifactId>testng</artifactId>
<version>6.14.3</version>
</dependency>

1. Create an excel file(excelfile.xls) and sheet name as (excelreader) with columns as (name,address,email) and one row with some values.
2.Point this to QAF dataProvider and give the sheetName as well.
3.In the @Test method, call data.get("name") and see you find get following exception.

Other Information: I'm using JDK 1.8 version.

**Comment by cjayswal** [comment] 2019-03-19 18:13
remove testng dependency from your pom and try.

**Comment by kabothu** [comment] 2019-03-19 18:16
@cjayswal : If I remove testng annotation, Could you please let me know how to import annotation for @Test()?

**Comment by cjayswal** [comment] 2019-03-19 18:19
Keep your code as it is. Remove TestNG dependency from you pom.xml it will automatically resolved by qaf.

**Comment by kabothu** [comment] 2019-03-19 18:25
@cjayswal : This way I can't use some of the default features of testng. We are forcing to use all the features of QAF and their respective syntaxes. Could you please confirm can I still use testng syntaxes or do i need to use QAF syntaxes?

**Comment by cjayswal** [comment] 2019-03-19 18:33
You will be able to utilize each and every feature of TestNG as QAF is [extension to TestNG](https://github.com/cbeust/testng/wiki/3rd-party-extensions#frameworks). QAF provides additional features on top of TestNG and you can use TestNG features as is with additional capabilities. Will you please provide details about syntaxes you are talking about?

**Comment by kabothu** [comment] 2019-03-19 18:37
Hi @cjayswal, I am talking about features like priority, grouping, dependsOnMethods etc. One more quick question, Is there a way i can map excel sheet columns to a Bean class Object and Pass the Bean Class Object to my test method something like @Test(BeanClass obj) and use object.getName() something like this?

**Comment by cjayswal** [comment] 2019-03-19 18:48
Defiantly you can use all the features of TestNG  including priority, grouping, dependsOnMethods etc. as your test is TestNG test. What i would suggest is try to overcome from the `NullPointerException` by removing testNG dependency from pom (or use 6.10 instead of 6.14.3). Once it resolved post your other queries into [users group](https://groups.google.com/forum/#!forum/qaf-users).

**Comment by kabothu** [comment] 2019-03-19 18:59
Sure. I will check and let you know.

**Comment by kabothu** [comment] 2019-03-19 23:37
@cjayswal : I removed testng dependency from pom and it shows an error in my Test Class asking me to import Testng annotation. It doesn't provide any suggestions from QAF. Can you please share me your code?

**Comment by cjayswal** [comment] 2019-03-19 23:39
[qaf-example-project.zip](https://github.com/qmetry/qaf/files/2985945/qaf-example-project.zip) is the working example you can try.

**Comment by kabothu** [comment] 2019-03-19 23:58
Your code works fine with lot of dependencies. Can you please check and let me know what am I missing? 
[ExcelCheck.zip](https://github.com/qmetry/qaf/files/2985974/ExcelCheck.zip)

**Comment by kabothu** [comment] 2019-03-20 00:49
@cjayswal : I figured it out the issue. If the package name is default package you will see that issue. It can be reproducible from your end as well. Please try and let me know

**Comment by cjayswal** [comment] 2019-03-20 00:50
Here you go [ExcelCheck.zip](https://github.com/qmetry/qaf/files/2986051/ExcelCheck.zip) with fix. I was able to reproduce the Null Pointer exception. The reason for the null pointer exception is that your test class was not in any package and that's why when looking for package it was throwing null pointer! You can move you test class in any package and it should start working. 

As a side not, you should extend appropriate base test case classeee from qaf depending on the functionality. For example: 
  - `TestNGTestCase` for none ui, none api
  - `WebdriverTestCase` for UI
  - `RestWSTestCase` for Web services 

Thanks for reporting bug and providing testcase to reproduce it. I will consider this bug not-critical because in real projects there is not use case i seen where test classes are in default package.

**Comment by kabothu** [comment] 2019-03-20 00:51
@cjayswal : Sounds great. and thanks for all your efforts and timely response. Appreciate it.

**Closed** 2019-03-30 17:23 UTC
Labels: bug, low
